new

diff --git a/roles/backup/templates/backup_suite.sh.j2 b/roles/backup/templates/backup_suite.sh.j2
--- a/roles/backup/templates/backup_suite.sh.j2
+++ b/roles/backup/templates/backup_suite.sh.j2
@@ -1,9 +1,19 @@
 #!/bin/bash
-DATE=$(date +%Y-%m-%d-%H%M%S)
-BACKUP_DIR="{{ backup_suite_dir }}"
+test_file="{{share_dir}}/DO_NOT_DELETE.txt"
+timeout="{{ mount_timeout }}"
+if [ ! -f "$test_file" ]; then mount "{{share_dir}}" > /dev/null  2>&1 ; fi
+if [ ! -f "$test_file" ]; then sleep $timeout; mount "{{share_dir}}" > /dev/null 2>&1; fi
+if [ ! -f "$test_file" ]; then echo "*****`date` share mount error, backup failed*****"; exit 1 ; fi
+
+DATA=`date +%Y-%m-%d`
+BACKUP_DIR="{{ share_dir }}"
 SOURCE="{{ source_suite_dir }}"
 cd  $SOURCE
-echo "*****`data` start suite backup*****"
-tar -cvzpf $BACKUP_DIR/backup-$DATE.tar.gz *
-echo "*****`data` complete suite backup*****"
+echo "*****`date` start suite backup*****"
+if [ -f ${BACKUP_DIR}/${DATA}/${DATA}_www_full.tar.gz ]; then
+  tar -czvpf ${BACKUP_DIR}/${DATA}/$(date +%Y-%m-%d-%H%M%S)_www_full.tar.gz *
+else
+  tar -czvpf ${BACKUP_DIR}/${DATA}/${DATA}_www_full.tar.gz *
+fi
+echo "*****`date` complete suite backup*****"
 echo ""
diff --git a/roles/backup/templates/diff_backup_db.sh.j2 b/roles/backup/templates/diff_backup_db.sh.j2
--- a/roles/backup/templates/diff_backup_db.sh.j2
+++ b/roles/backup/templates/diff_backup_db.sh.j2
@@ -1,13 +1,20 @@
 #!/bin/bash
 DATA1=`date +%Y-%m-%d`
 DATA2=`date +%H-%M-%S`
-BACKUP_DIR="{{ diff_backup_db_dir }}"
+SHARE_DIR="{{ share_dir }}"
+BACKUP_DIR="{{ backup_dir }}"
 
+test_file="{{share_dir}}/DO_NOT_DELETE.txt"
+timeout="{{ mount_timeout }}"
+if [ ! -f "$test_file" ]; then mount "{{share_dir}}" > /dev/null  2>&1 ; fi
+if [ ! -f "$test_file" ]; then sleep $timeout; mount "{{share_dir}}" > /dev/null 2>&1; fi
+if [ ! -f "$test_file" ]; then echo "*****`date` share mount error, backup failed*****"; exit 1 ; fi
 
-echo "*****`data` start full backup*****"
-xtrabackup --backup --target-dir=$BACKUP_DIR/$DATA1/diff-$DATA2 --user=root --diffremental-basedir=$BACKUP_DIR/$DATA1/full
-cd $BACKUP_DIR/$DATA1/diff-$DATA2
-tar -czvf $BACKUP_DIR/$DATA1/diff-$DATA2.tar.gz *
-rm -rf $BACKUP_DIR/$DATA1/diff-$DATA2
-echo "*****`data` complete full backup*****"
+echo "*****`date` start diff backup*****"
+xtrabackup --backup --target-dir=$BACKUP_DIR/diff-$DATA2 --user=root --incremental-basedir=$BACKUP_DIR/full
+cd $BACKUP_DIR/diff-$DATA2
+tar -czvf ${SHARE_DIR}/${DATA1}/${DATA2}_db_diff.tar.gz *
+rm -rf $BACKUP_DIR/diff-$DATA2
+echo "*****`date` complete diff backup*****"
 echo ""
+
diff --git a/roles/backup/templates/full_backup_db.sh.j2 b/roles/backup/templates/full_backup_db.sh.j2
--- a/roles/backup/templates/full_backup_db.sh.j2
+++ b/roles/backup/templates/full_backup_db.sh.j2
@@ -1,13 +1,28 @@
 #!/bin/bash
 DATA=`date +%Y-%m-%d`
-BACKUP_DIR="{{ full_backup_db_dir }}"
+SHARE_DIR="{{ share_dir }}"
+BACKUP_DIR="{{ backup_dir }}"
 
-cd  $SOURCE
-echo "*****`data` start full backup*****"
-mkdir -p $BACKUP_DIR/$DATA
-xtrabackup --backup --user=root --target-dir=$BACKUP_DIR/$DATA/full
-xtrabackup --prepare —target-dir=$BACKUP_DIR/$DATA/full
-cd $BACKUP_DIR/$DATA/
-tar -czvf $BACKUP_DIR/$DATA/full.tar.gz *
-echo "*****`data` complete full backup*****"
+test_file="{{share_dir}}/DO_NOT_DELETE.txt"
+timeout="{{ mount_timeout }}"
+if [ ! -f "$test_file" ]; then mount "{{share_dir}}" > /dev/null  2>&1 ; fi
+if [ ! -f "$test_file" ]; then sleep $timeout; mount "{{share_dir}}" > /dev/null 2>&1; fi
+if [ ! -f "$test_file" ]; then echo "*****`date` share mount error, backup failed*****"; exit 1 ; fi
+
+echo "*****`date` start full backup*****"
+if [ -f ${SHARE_DIR}/${DATA}/${DATA}_db_full.tar.gz ]; then
+  xtrabackup --backup --user=root --target-dir=$BACKUP_DIR/full_tmp
+  xtrabackup --prepare —target-dir=$BACKUP_DIR/full_tmp
+  cd $BACKUP_DIR/full_tmp/
+  tar -czvf ${SHARE_DIR}/${DATA}/$(date +%Y-%m-%d-%H%M%S)_db_full.tar.gz *
+  rm -rf $BACKUP_DIR/full_tmp/
+else
+  rm -rf $BACKUP_DIR/full/*
+  mkdir -p $SHARE_DIR/$DATA
+  xtrabackup --backup --user=root --target-dir=$BACKUP_DIR/full
+  xtrabackup --prepare —target-dir=$BACKUP_DIR/full
+  cd $BACKUP_DIR/full/
+  tar -czvf ${SHARE_DIR}/${DATA}/${DATA}_db_full.tar.gz *
+fi
+echo "*****`date` complete full backup*****"
 echo ""
